spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/security1
    username: security1
    password: security1
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security.web: trace